config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :vulnerabilities
  resources :assets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
    has_many :vulnerabilities

    validates :name, presence:true
    validates :description, presence:true
    validates :os, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:name, :description, :os)
    end
end

app/controllers/vulnerabilities_controller.rb
class VulnerabilitiesController < ApplicationController
  before_action :set_vulnerability, only: [:show, :edit, :update, :destroy]

  # GET /vulnerabilities
  # GET /vulnerabilities.json
  def index
    @vulnerabilities = Vulnerability.all
  end

  # GET /vulnerabilities/1
  # GET /vulnerabilities/1.json
  def show
  end

  # GET /vulnerabilities/new
  def new
    @vulnerability = Vulnerability.new
  end

  # GET /vulnerabilities/1/edit
  def edit
  end

  # POST /vulnerabilities
  # POST /vulnerabilities.json
  def create
    @vulnerability = Vulnerability.new(vulnerability_params)

    respond_to do |format|
      if @vulnerability.save
        format.html { redirect_to @vulnerability, notice: 'Vulnerability was successfully created.' }
        format.json { render :show, status: :created, location: @vulnerability }
      else
        format.html { render :new }
        format.json { render json: @vulnerability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vulnerabilities/1
  # PATCH/PUT /vulnerabilities/1.json
  def update
    respond_to do |format|
      if @vulnerability.update(vulnerability_params)
        format.html { redirect_to @vulnerability, notice: 'Vulnerability was successfully updated.' }
        format.json { render :show, status: :ok, location: @vulnerability }
      else
        format.html { render :edit }
        format.json { render json: @vulnerability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vulnerabilities/1
  # DELETE /vulnerabilities/1.json
  def destroy
    @vulnerability.destroy
    respond_to do |format|
      format.html { redirect_to vulnerabilities_url, notice: 'Vulnerability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vulnerability
      @vulnerability = Vulnerability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vulnerability_params
      params.require(:vulnerability).permit(:name, :description, :criticality, :solution, :cvss_score, :asset_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/vulnerabilities_helper.rb
module VulnerabilitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assets/_form.html.erb
<%= form_with(model: asset, local: true) do |form| %>
  <% if asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= form.label :name %></b>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <b><%= form.label :description %></b>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <b><%= form.label :os %></b>
    <%= form.text_field :os %>
  </div>

  <div class="actions">
    <%= form.submit :class=> 'white-text waves-effect waves-light btn' %>
  </div>
  
<% end %>

app/views/assets/edit.html.erb
<%= react_component 'Menubar' %>

<br><br><br>

<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>
<br>
<%= link_to 'Show', @asset, class: "white-text waves-effect waves-light btn" %>
<%= link_to 'Back', assets_path, class: "white-text waves-effect waves-light btn" %>

app/views/assets/index.html.erb
<%= react_component 'Menubar' %>

<p id="notice"><%= notice %></p>

<br><br><br>

<h1>Assets</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Os</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.name %></td>
        <td><%= asset.description %></td>
        <td><%= asset.os %></td>
        <td><%= link_to 'Show', asset, class: 'white-text waves-effect waves-light btn-small' %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset), class: 'white-text waves-effect waves-light btn-small' %></td>
        <td><%= link_to 'Destroy', asset, class: 'white-text waves-effect waves-light btn-small', method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path(@asset), :class=> 'white-text waves-effect waves-light btn' %>

<br><br><br><br>
<%= pie_chart Asset.group(:name).count %>

app/views/assets/new.html.erb
<%= react_component 'Menubar' %>

<br><br><br>

<h1>New Asset</h1>

<%= render 'form', asset: @asset %>

<br>

<%= link_to 'Back', assets_path, class: "white-text waves-effect waves-light btn" %>

app/views/assets/show.html.erb
<%= react_component 'Menubar' %>

<br><br><br><br><br>

<p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">

            <p>
              <strong>NAME</strong>
              <%= @asset.name %>
            </p>

          </div>
        </div>
      </div>
    </div>


    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">

            <p>
              <strong>DESCRIPTION</strong>
              <%= @asset.description %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">

            <p>
              <strong>OS:</strong>
              <%= @asset.os %>
            </p>

          </div>
        </div>
      </div>
    </div>
  </div>

  <br>
  <%= link_to 'Edit', edit_asset_path(@asset), :class=> 'white-text waves-effect waves-light btn' %>
  <%= link_to 'Back', assets_path, :class=> 'white-text waves-effect waves-light btn' %>

<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Following will make the react components availabe to our layout -->
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/vulnerabilities/_form.html.erb
<%= form_with(model: vulnerability, local: true) do |form| %>
  <% if vulnerability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vulnerability.errors.count, "error") %> prohibited this vulnerability from being saved:</h2>

      <ul>
      <% vulnerability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= form.label :name %></b>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <b><%= form.label :description %></b>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <b><%= form.label :criticality %></b>
    <%= form.select :criticality, ['Baixa', 'Média', 'Alto', 'Crítica'], {include_blank: "Select..." } %>
  </div>

  <div class="field">
    <b><%= form.label :solution %></b>
    <%= form.text_field :solution %>
  </div>

  <div class="field">
    <b><%= form.label :cvss_score %></b>
    <%= form.number_field :cvss_score %>
  </div>

  <div class="field">
    <b><%= form.label :asset %></b>
    <%= form.select("asset_id", Asset.all.collect {|a| [a.name, a.id ]}, {include_blank: "Select..." }  )%>
  </div>

<br>
  <div class="actions">
    <%= form.submit :class=> 'white-text waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/vulnerabilities/edit.html.erb
<%= react_component 'Menubar' %>

<br><br><br>

<h1>Editing Vulnerability</h1>

<%= render 'form', vulnerability: @vulnerability %>
<br>
<%= link_to 'Show', @vulnerability, class: "white-text waves-effect waves-light btn" %>
<%= link_to 'Back', vulnerabilities_path, class: "white-text waves-effect waves-light btn" %>

<br><br>

app/views/vulnerabilities/index.html.erb
<%= react_component 'Menubar' %>

<p id="notice"><%= notice %></p>

<br><br><br>

<h1>Vulnerabilities</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Criticality</th>
      <th>Solution</th>
      <th>Cvss score</th>
      <th>Asset</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vulnerabilities.each do |vulnerability| %>
      <tr>
        <td><%= vulnerability.name %></td>
        <td><%= vulnerability.description %></td>
        <td><%= vulnerability.criticality %></td>
        <td><%= vulnerability.solution %></td>
        <td><%= vulnerability.cvss_score %></td>
        <td><%= vulnerability.asset.name %></td>
        <td><%= link_to 'Show', vulnerability, class: 'white-text waves-effect waves-light btn-small' %></td>
        <td><%= link_to 'Edit', edit_vulnerability_path(vulnerability), class: 'white-text waves-effect waves-light btn-small' %></td>
        <td><%= link_to 'Destroy', vulnerability, method: :delete, data: { confirm: 'Are you sure?' }, class: 'white-text waves-effect waves-light btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="red-text">
<%= link_to 'New Vulnerability', new_vulnerability_path, class: "white-text waves-effect waves-light btn" %>
</div>

<br><br>
<%= pie_chart Vulnerability.group(:criticality).count %>

<%= pie_chart Asset.group(:name).count %>

app/views/vulnerabilities/new.html.erb
<%= react_component 'Menubar' %>

<br><br><br>

<h1>New Vulnerability</h1>

<%= render 'form', vulnerability: @vulnerability %>

<br>

<%= link_to 'Back', vulnerabilities_path, class: "white-text waves-effect waves-light btn-small" %>

<br>
<br>

app/views/vulnerabilities/show.html.erb
<%= react_component 'Menubar' %>

<br><br><br><br><br>

<p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-sm-4">
     <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <p>
              <strong>Name:</strong>
              <%= @vulnerability.name %>
            </p>
          </div>
        </div>  
      </div> 
    </div>

    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <p>
                <strong>Description:</strong>
                <%= @vulnerability.description %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-4">  
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <p>
              <strong>Criticality:</strong>
              <%= @vulnerability.criticality %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <p>
              <strong>Solution:</strong>
              <%= @vulnerability.solution %>
            </p>
          </div>
        </div>
      </div>
    </div>


    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <p>
              <strong>Cvss score:</strong>
              <%= @vulnerability.cvss_score %>
            </p>
          </div>
        </div>
      </div>
    </div>
    
  </div>


  <br>
  <%= link_to 'Edit', edit_vulnerability_path(@vulnerability), :class=> 'white-text waves-effect waves-light btn' %>
  <%= link_to 'Back', vulnerabilities_path, :class=> 'white-text waves-effect waves-light btn' %>

<br><br>

app/views/welcome/index.html.erb
<%= react_component 'Menubar' %>

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport"
    content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    
<head>

<body>
    
    <header class="v-header container">
        
        <div class= "header-overlay"></div>

        <div class= "fullscreen-video-wrap">
            <%= video_tag "bg.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "home_video" %>
        <div>
        
        <div class="welcome">
            Welcome  

            <div class="description">
            to New Box
        </div>

        </div>

    </header>
</body>

<html>